// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElTag: typeof import('element-plus/es')['ElTag']
    IEpEleme: typeof import('~icons/ep/eleme')['default']
    IEpElementPlus: typeof import('~icons/ep/element-plus')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IIconsTest: typeof import('~icons/icons/test')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
